# Generated by Django 5.2.7 on 2025-11-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(blank=True, default=None, null=True, verbose_name='性别')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'orm_student',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='个性签名')),
                ('address', models.CharField(max_length=500, verbose_name='家庭住址')),
                ('mobile', models.CharField(max_length=15, verbose_name='紧急联系人')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='orm.student')),
            ],
            options={
                'verbose_name': '学生详细信息',
                'verbose_name_plural': '学生详细信息',
                'db_table': 'orm_student_profile',
            },
        ),
    ]
