# Generated by Django 5.2.7 on 2025-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_author_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='文章内容'),
        ),
    ]
