# Generated by Django 5.2.7 on 2025-11-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(blank=True, default=None, null=True, verbose_name='性别')),
            ],
            options={
                'verbose_name': '老师信息',
                'verbose_name_plural': '老师信息',
                'db_table': 'orm_teacher',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='课程名称')),
                ('teacher', models.ManyToManyField(related_name='course', to='orm.teacher')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
                'db_table': 'orm_course',
            },
        ),
    ]
