# Generated by Django 5.2.7 on 2025-11-16 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='省市名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='orm.area')),
            ],
            options={
                'verbose_name': '行政划分表',
                'verbose_name_plural': '行政划分表',
                'db_table': 'orm_area',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('age', models.SmallIntegerField(default=0, verbose_name='年龄')),
                ('friends', models.ManyToManyField(to='orm.user')),
            ],
            options={
                'verbose_name': '好友关注表',
                'verbose_name_plural': '好友关注表',
                'db_table': 'orm_user',
            },
        ),
    ]
