# Generated by Django 5.2.7 on 2025-11-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_area_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'orm_city',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='省份')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'db_table': 'orm_province',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='姓')),
                ('lastname', models.CharField(max_length=20, verbose_name='名')),
                ('hometown', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hometown_people', to='orm.city', verbose_name='家乡')),
                ('living', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='living_people', to='orm.city', verbose_name='居住地')),
                ('visitation', models.ManyToManyField(related_name='visit_people', to='orm.city', verbose_name='旅游地')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'orm_person',
            },
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, verbose_name='电话号码')),
                ('wechat', models.CharField(max_length=50, verbose_name='微信号')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='orm.person')),
            ],
            options={
                'verbose_name': '用户详细信息',
                'verbose_name_plural': '用户详细信息',
                'db_table': 'orm_profile',
            },
        ),
    ]
