# Generated by Django 5.2.7 on 2025-11-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_city_province_person_personprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='orm.province', verbose_name='省份'),
        ),
    ]
