# Generated by Django 5.2.7 on 2025-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='软件名称')),
                ('version', models.CharField(max_length=50, verbose_name='软件版本')),
                ('website', models.URLField(max_length=500, verbose_name='公司网站')),
                ('picture', models.ImageField(upload_to='software/%Y/%m/%d/', verbose_name='缩略图')),
                ('downloads', models.FileField(upload_to='attr/%Y/%m/%d/', verbose_name='下载地址')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': '应用管理',
                'db_table': 'tb_software',
            },
        ),
    ]
