# Generated by Django 5.2.7 on 2025-11-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_create_time_student_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '未入学'), (1, '在校'), (2, '已毕业')], default=1, null=True, verbose_name='毕业情况'),
        ),
    ]
