# Generated by Django 5.2.7 on 2025-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_create_time_student_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
    ]
