# Generated by Django 5.2.7 on 2025-11-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default=True, max_length=10, verbose_name='性别'),
        ),
    ]
