# Generated by Django 5.2.7 on 2025-11-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeldemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Female',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modeldemo.user',),
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modeldemo.user',),
        ),
    ]
